################################################################################
# This is a reusable YAML template, referenced by other files:
#   ./ci.yaml
#   ./npm-publish-rush.yaml
#   ./npm-publish.yaml
#
# (See common/config/azure-pipelines/README.md for more information.)
# Schema: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
################################################################################
steps:
  - task: NodeTool@0
    displayName: 'Use Node $(NodeVersion).x'
    inputs:
      versionSpec: '$(NodeVersion).x'
      checkLatest: true
  - script: 'git config --local user.email rushbot@users.noreply.github.com'
    displayName: 'git config email'
  - script: 'git config --local user.name Rushbot'
    displayName: 'git config name'
  - script: 'node common/scripts/install-run-rush.js change --verify'
    displayName: 'Verify Change Logs'
  - script: 'node common/scripts/install-run-rush.js install'
    displayName: 'Rush Install'
  - script: 'node common/scripts/install-run-rush.js rebuild --verbose --production'
    displayName: 'Rush Rebuild'
    env:
      # Prevent time-based browserslist update warning
      # See https://github.com/microsoft/rushstack/issues/2981
      BROWSERSLIST_IGNORE_OLD_DATA: 1
