################################################################################
# This is a reusable YAML template, referenced by other files:
#   ./npm-publish-rush.yaml
#   ./npm-publish.yaml
#
# (See common/config/azure-pipelines/README.md for more information.)
# Schema: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
################################################################################
parameters:
  - name: VersionPolicyName
    type: string
steps:
  - script: 'node common/scripts/install-run-rush.js version --bump --version-policy ${{ parameters.VersionPolicyName }} --target-branch $(Build.SourceBranchName)'
    displayName: 'Rush Version (Policy: ${{ parameters.VersionPolicyName }})'
  - script: 'node common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch $(Build.SourceBranchName) --add-commit-details --set-access-level public'
    displayName: 'Rush Publish (Policy: ${{ parameters.VersionPolicyName }})'
    env:
      NPM_AUTH_TOKEN: $(npmToken)
